### PR TITLE
Added screenshots

### PR DESCRIPTION
**Pull request by lgrkvst**
Bummer having to install every theme in order to see them in action, so examples added.

For footprint it might make sense to move the image files to a separate repo and relink readme.md.

### CODE REVIEW

**Comment by lgrkvst** [comment]
Label check failed, but I can't seem to add any...

**Comment by bonanitech** [comment]
Hey, @lgrkvst! Thank you for this PR.

> Bummer having to install every theme in order to see them in action

I agree with you. But we need to find a better way to add the screenshots.

On [npmjs.com](https://www.npmjs.com/package/@node-red-contrib-themes/theme-collection), it would be weird navigating through the screenshots and the readme.

**Comment by lgrkvst** [comment]
I think the only difference on npmjs would be another column of links on the themes table (images are not shown inline). But perhaps the repo's footprint is better off with the screenshots in a separate repo.

**Comment by bonanitech** [comment]
Closing this in favor of #314. Thank you for the suggestion, @lgrkvst.

**Pull request closed without merging**
